export function cacheDomElements() {
  return {
    // Splash
    splashScreen: document.getElementById('splash-screen'),
    splashStatus: document.querySelector('.splash-status'),

    // Overlays
    onboardingOverlay: document.getElementById('onboarding-overlay'),
    discoveryDashboard: document.getElementById('discovery-dashboard'),
    app: document.getElementById('app'),

    // Onboarding
    btnSelectFolder: document.getElementById('btn-select-folder'),
    scanProgress: document.getElementById('scan-progress'),
    scanStatus: document.querySelector('.scan-status'),
    browserWarning: document.getElementById('browser-warning'),

    // Dashboard
    discoverySummary: document.getElementById('discovery-summary'),
    modelsList: document.getElementById('models-list'),
    btnToggleSelection: document.getElementById('btn-toggle-selection'),
    btnOpenLanguageFilter: document.getElementById('btn-open-language-filter'),
    languageFilterCount: document.getElementById('language-filter-count'),
    selectionInfo: document.getElementById('selection-info'),
    btnStartIndexing: document.getElementById('btn-start-indexing'),
    btnCancelRescan: document.getElementById('btn-cancel-rescan'),
    btnChangeFolder: document.getElementById('btn-change-folder'),
    btnOpenAdvancedSelection: document.getElementById('btn-open-advanced-selection'),
    indexingProgress: document.getElementById('indexing-progress'),
    progressFill: document.getElementById('progress-fill'),
    indexingStatus: document.getElementById('indexing-status'),
    advancedSelectionModal: document.getElementById('advanced-selection-modal'),
    btnCloseAdvancedSelectionModal: document.getElementById('btn-close-advanced-selection-modal'),
    btnCloseAdvancedSelection: document.getElementById('btn-close-advanced-selection'),
    btnStartIndexingModal: document.getElementById('btn-start-indexing-modal'),

    // Language Filter Modal
    languageFilterModal: document.getElementById('language-filter-modal'),
    btnCloseLanguageFilterModal: document.getElementById('btn-close-language-filter-modal'),
    languageFilterSearch: document.getElementById('language-filter-search'),
    btnToggleAllLanguages: document.getElementById('btn-toggle-all-languages'),
    languageFilterList: document.getElementById('language-filter-list'),
    btnApplyLanguageFilter: document.getElementById('btn-apply-language-filter'),

    // Header
    labelCountBadge: document.getElementById('label-count-badge'),
    lastIndexed: document.getElementById('last-indexed'),
    btnRescan: document.getElementById('btn-rescan'),
    btnHeaderChangeFolder: document.getElementById('btn-header-change-folder'),
    btnBackgroundTasks: document.getElementById('btn-background-tasks'),
    backgroundTasksText: document.getElementById('background-tasks-text'),
    btnAiDownloadStatus: document.getElementById('btn-ai-download-status'),
    aiDownloadStatusText: document.getElementById('ai-download-status-text'),
    btnShortcutsHelp: document.getElementById('btn-shortcuts-help'),

    // Search
    searchInput: document.getElementById('search-input'),
    clearSearch: document.getElementById('clear-search'),
    searchInfo: document.getElementById('search-info'),
    btnAdvancedSearch: document.getElementById('btn-advanced-search'),
    btnSystemSettings: document.getElementById('btn-system-settings'),
    activeFilters: document.getElementById('active-filters'),
    resultsCount: document.getElementById('results-count'),
    sortSelect: document.getElementById('sort-select'),

    // Advanced Search Modal
    advancedSearchModal: document.getElementById('advanced-search-modal'),
    btnCloseModal: document.getElementById('btn-close-modal'),
    modalModels: document.getElementById('modal-models'),
    modalLanguages: document.getElementById('modal-languages'),
    modalExactMatch: document.getElementById('modal-exact-match'),
    modalUseBloomFilter: document.getElementById('modal-use-bloom-filter'),
    modalHideIncomplete: document.getElementById('modal-hide-incomplete'),
    selectedModelsSummary: document.getElementById('selected-models-summary'),
    selectedLanguagesSummary: document.getElementById('selected-languages-summary'),
    requiredLanguagesSummary: document.getElementById('required-languages-summary'),
    btnOpenModelSelector: document.getElementById('btn-open-model-selector'),
    btnOpenLanguageSelector: document.getElementById('btn-open-language-selector'),
    btnOpenRequiredLanguageSelector: document.getElementById('btn-open-required-language-selector'),
    modalGroupDuplicates: document.getElementById('modal-group-duplicates'),
    formatFull: document.getElementById('format-full'),
    formatSimple: document.getElementById('format-simple'),
    formatHybrid: document.getElementById('format-hybrid'),
    btnClearFilters: document.getElementById('btn-clear-filters'),
    btnApplyFilters: document.getElementById('btn-apply-filters'),

    // System Settings Modal
    systemSettingsModal: document.getElementById('system-settings-modal'),
    btnCloseSettingsModal: document.getElementById('btn-close-settings-modal'),
    btnApplySettings: document.getElementById('btn-apply-settings'),
    uiLanguageSelect: document.getElementById('ui-language-select'),
    settingDirectSaveMode: document.getElementById('setting-direct-save-mode'),
    // SPEC-35: AI & Intelligence settings
    settingAiEnabled: document.getElementById('setting-ai-enabled'),
    btnAiDownloadModel: document.getElementById('btn-ai-download-model'),
    aiStatusBadge: document.getElementById('ai-status-badge'),
    aiDownloadProgress: document.getElementById('ai-download-progress'),
    aiDownloadFill: document.getElementById('ai-download-fill'),
    aiDownloadLabel: document.getElementById('ai-download-label'),
    aiUnlockedOptions: document.getElementById('ai-unlocked-options'),
    aiLockedHint: document.getElementById('ai-locked-hint'),
    settingAiSemanticId: document.getElementById('setting-ai-semantic-id'),
    settingAiAutoTranslate: document.getElementById('setting-ai-auto-translate'),
    settingAiSourceLanguage: document.getElementById('setting-ai-source-language'),
    settingAiTargetLanguage: document.getElementById('setting-ai-target-language'),
    btnAiClearCache: document.getElementById('btn-ai-clear-cache'),
    // SPEC-19: Hybrid Search Settings
    settingHybridSearch: document.getElementById('setting-hybrid-search'),
    settingMaxModels: document.getElementById('setting-max-models'),
    settingFuzzyThreshold: document.getElementById('setting-fuzzy-threshold'),
    fuzzyThresholdValue: document.getElementById('fuzzy-threshold-value'),

    // Generic Selector Modal
    itemSelectorModal: document.getElementById('item-selector-modal'),
    itemSelectorTitle: document.getElementById('item-selector-title'),
    itemSelectorSearch: document.getElementById('item-selector-search'),
    itemSelectorList: document.getElementById('item-selector-list'),
    btnToggleAllSelector: document.getElementById('btn-toggle-all-selector'),
    btnCloseSelectorModal: document.getElementById('btn-close-selector-modal'),
    btnCloseSelector: document.getElementById('btn-close-selector'),

    // Label Details Modal
    labelDetailsModal: document.getElementById('label-details-modal'),
    btnCloseDetailsModal: document.getElementById('btn-close-details-modal'),
    btnCloseDetails: document.getElementById('btn-close-details'),
    labelDetailsContent: document.getElementById('label-details-content'),

    // Shortcuts Modal
    shortcutsModal: document.getElementById('shortcuts-modal'),
    btnCloseShortcutsModal: document.getElementById('btn-close-shortcuts-modal'),
    btnCloseShortcuts: document.getElementById('btn-close-shortcuts'),

    // Results
    resultsToolbar: document.getElementById('results-toolbar'),
    liveIndexLine: document.getElementById('live-index-line'),
    liveIndexLineFill: document.getElementById('live-index-line-fill'),
    resultsContainer: document.getElementById('results-container'),
    resultsViewport: document.getElementById('results-viewport'),
    resultsInner: document.getElementById('results-inner'),
    emptyState: document.getElementById('empty-state'),
    loadingState: document.getElementById('loading-state'),

    // SPEC-23: Tiered Discovery
    priorityLanguageChips: document.getElementById('priority-language-chips'),
    priorityFilesCount: document.getElementById('priority-files-count'),
    btnQuickStart: document.getElementById('btn-quick-start'),
    chkBackgroundIndexing: document.getElementById('chk-background-indexing'),

    // SPEC-23: Background Progress
    btnBackgroundProgress: document.getElementById('btn-background-progress'),
    backgroundProgressModal: document.getElementById('background-progress-modal'),
    btnCloseBackgroundProgress: document.getElementById('btn-close-background-progress'),
    bgTotalLabels: document.getElementById('bg-total-labels'),
    bgTotalPercent: document.getElementById('bg-total-percent'),
    bgEta: document.getElementById('bg-eta'),
    bgSpeed: document.getElementById('bg-speed'),
    bgProgressFill: document.getElementById('bg-progress-fill'),
    bgLanguageList: document.getElementById('bg-language-list'),
    bgSummary: document.getElementById('bg-summary'),

    // SPEC-29: Advanced Stats Dashboard
    statsDashboardModal: document.getElementById('stats-dashboard-modal'),
    btnCloseStatsDashboard: document.getElementById('btn-close-stats-dashboard'),
    statsTotalModels: document.getElementById('stats-total-models'),
    statsTotalFiles: document.getElementById('stats-total-files'),
    statsTotalSize: document.getElementById('stats-total-size'),
    statsGlobalSpeed: document.getElementById('stats-global-speed'),
    statsModelList: document.getElementById('stats-model-list'),
    statsPairList: document.getElementById('stats-pair-list'),

    // SPEC-36: Tools Menu
    btnToolsMenu: document.getElementById('btn-tools-menu'),
    toolsModal: document.getElementById('tools-modal'),
    btnCloseToolsModal: document.getElementById('btn-close-tools-modal'),
    btnCloseTools: document.getElementById('btn-close-tools'),
    btnToolMerger: document.getElementById('btn-tool-merger'),
    btnToolBuilder: document.getElementById('btn-tool-builder'),
    btnToolExtractor: document.getElementById('btn-tool-extractor'),

    // SPEC-36: Merger Modal
    mergerModal: document.getElementById('merger-modal'),
    btnCloseMergerModal: document.getElementById('btn-close-merger-modal'),
    mergerDropzone: document.getElementById('merger-dropzone'),
    btnMergerSelectFiles: document.getElementById('btn-merger-select-files'),
    mergerFileList: document.getElementById('merger-file-list'),
    mergerFilesContainer: document.getElementById('merger-files-container'),
    btnMergerAddMore: document.getElementById('btn-merger-add-more'),
    btnMergerClearFiles: document.getElementById('btn-merger-clear-files'),
    mergerStepFiles: document.getElementById('merger-step-files'),
    mergerStepResults: document.getElementById('merger-step-results'),
    mergerTotalLabels: document.getElementById('merger-total-labels'),
    mergerDuplicates: document.getElementById('merger-duplicates'),
    mergerConflicts: document.getElementById('merger-conflicts'),
    mergerConflictsSection: document.getElementById('merger-conflicts-section'),
    mergerConflictsList: document.getElementById('merger-conflicts-list'),
    mergerPreviewContent: document.getElementById('merger-preview-content'),
    btnMergerBack: document.getElementById('btn-merger-back'),
    btnMergerMerge: document.getElementById('btn-merger-merge'),
    btnMergerDownload: document.getElementById('btn-merger-download'),

    // SPEC-32: Builder Modal
    builderModal: document.getElementById('builder-modal'),
    btnCloseBuilderModal: document.getElementById('btn-close-builder-modal'),
    builderCountBadge: document.getElementById('builder-count-badge'),
    builderDirectSaveWarning: document.getElementById('builder-direct-save-warning'),
    btnBuilderNew: document.getElementById('btn-builder-new'),
    btnBuilderClear: document.getElementById('btn-builder-clear'),
    builderCultureSelect: document.getElementById('builder-culture-select'),
    builderSourceLanguage: document.getElementById('builder-source-language'),
    builderTargetLanguages: document.getElementById('builder-target-languages'),
    btnBuilderAutoTranslate: document.getElementById('btn-builder-auto-translate'),
    builderTranslateProgress: document.getElementById('builder-translate-progress'),
    builderTranslateFill: document.getElementById('builder-translate-fill'),
    builderTranslateLabel: document.getElementById('builder-translate-label'),
    builderWorkspace: document.getElementById('builder-workspace'),
    builderEmptyState: document.getElementById('builder-empty-state'),
    builderItemsContainer: document.getElementById('builder-items-list'),
    btnBuilderDownload: document.getElementById('btn-builder-download'),
    btnBuilderFinish: document.getElementById('btn-builder-finish'),

    // SPEC-32: New Label Modal
    newLabelModal: document.getElementById('new-label-modal'),
    btnCloseNewLabelModal: document.getElementById('btn-close-new-label-modal'),
    inputNewLabelId: document.getElementById('new-label-id'),
    inputNewLabelText: document.getElementById('new-label-text'),
    inputNewLabelHelp: document.getElementById('new-label-help'),
    inputNewLabelPrefix: document.getElementById('new-label-prefix'),
    btnCancelNewLabel: document.getElementById('btn-cancel-new-label'),
    btnSaveNewLabel: document.getElementById('btn-save-new-label'),

    // SPEC-32: Conflict Modal
    conflictModal: document.getElementById('conflict-modal'),
    btnCloseConflictModal: document.getElementById('btn-close-conflict-modal'),
    conflictMessage: document.getElementById('conflict-message'),
    conflictExistingId: document.getElementById('conflict-existing-id'),
    conflictExistingText: document.getElementById('conflict-existing-text'),
    conflictExistingHelp: document.getElementById('conflict-existing-help'),
    conflictIncomingId: document.getElementById('conflict-incoming-id'),
    conflictIncomingText: document.getElementById('conflict-incoming-text'),
    conflictIncomingHelp: document.getElementById('conflict-incoming-help'),
    btnConflictRename: document.getElementById('btn-conflict-rename'),
    btnConflictEdit: document.getElementById('btn-conflict-edit'),
    btnConflictOverwrite: document.getElementById('btn-conflict-overwrite'),
    btnConflictSkip: document.getElementById('btn-conflict-skip'),

    // Export Modal (SPEC-32/33 multi-language + ZIP)
    exportModal: document.getElementById('builder-export-modal'),
    btnCloseExportModal: document.getElementById('btn-close-export-modal'),
    exportSourceCulture: document.getElementById('export-source-culture'),
    exportLabelCount: document.getElementById('export-label-count'),
    exportLanguageCheckboxes: document.getElementById('export-language-checkboxes'),
    exportAiWarning: document.getElementById('export-ai-warning'),
    exportFilePrefix: document.getElementById('export-file-prefix'),
    exportProgressSection: document.getElementById('export-progress-section'),
    exportProgressFill: document.getElementById('export-progress-fill'),
    exportProgressLabel: document.getElementById('export-progress-label'),
    btnExportCancel: document.getElementById('btn-export-cancel'),
    btnExportGenerate: document.getElementById('btn-export-generate'),

    // SPEC-34: Hardcoded String Extractor (Redesigned Workspace)
    extractorWorkspace: document.getElementById('extractor-workspace'),
    btnExtractorClose: document.getElementById('btn-extractor-close'),
    btnExtractorSelectProject: document.getElementById('btn-extractor-select-project'),
    btnExtractorSelectFiles: document.getElementById('btn-extractor-select-files'),
    btnExtractorStart: document.getElementById('btn-extractor-start'),
    extractorStatusBadge: document.getElementById('extractor-status-badge'),
    extractorProjectInfo: document.getElementById('extractor-project-info'),
    extractorProjectName: document.getElementById('extractor-project-name'),
    extractorProjectModel: document.getElementById('extractor-project-model'),
    extractorFileTree: document.getElementById('extractor-file-tree'),
    extractorFilesCount: document.getElementById('extractor-files-count'),
    extractorFilesScanned: document.getElementById('extractor-files-scanned'),
    extractorTargetFile: document.getElementById('extractor-target-file'),
    extractorProgress: document.getElementById('extractor-progress'),
    extractorProgressFill: document.getElementById('extractor-progress-fill'),
    extractorProgressLabel: document.getElementById('extractor-progress-label'),
    extractorSummary: document.getElementById('extractor-summary'),
    extractorTotalFound: document.getElementById('extractor-total-found'),
    extractorResolvedCount: document.getElementById('extractor-resolved-count'),
    extractorIgnoredCount: document.getElementById('extractor-ignored-count'),
    extractorResults: document.getElementById('extractor-results'),
    extractorAutoSave: document.getElementById('extractor-auto-save'),
    btnExtractorAddAll: document.getElementById('btn-extractor-add-all'),
    btnExtractorApply: document.getElementById('btn-extractor-apply'),
    btnExtractorRollback: document.getElementById('btn-extractor-rollback')
  };
}
